name: Scheduled ETL Process

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Recreate the service_account.json file
      - name: Create service account file
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run ETL Script
      - name: Run ETL Script
        env:
          folder_id: ${{ secrets.folder_id }}
          motherduck_dsn: ${{ secrets.motherduck_dsn }}
        run: python etl_script.py
